services:
  postgres:
    image: postgres:16-alpine
    container_name: stat-force-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: statforce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - stat-force-postgres:/var/lib/postgresql/data

volumes:
  stat-force-postgres:
